### ISSUE TITLE
Csound iOS SwiftExamples crashes on iOS device

### ISSUE THREAD

**Issue by Megal** [csound/csound#2111]
I'm experience a crash when trying to run iOS swift example from develop.

commit: https://github.com/csound/csound/commit/f528965667ad6eeecdd24ea07872a40958ef13ce
artifact: https://github.com/csound/csound/actions/runs/13726924626/artifacts/2712894617
XCode: 16.2
CPU: M1 Pro
macOS: 15.3.1
iOS: 16.0

Steps to reproduce:
1. Download artifact, unarchive, open Csound iOS SwiftExamples.xcodeproj
2. Build - compilation error libs are missing
3. Fix it by removing libs from project and adding libSndfileiOS.xcframework and CsoundiOS.xcframework
4. Compilation now successful
5. Crash when clicking on switch on first test view controller.

Crased at CsoundObj.m:369:36
Following backtrace: 
```
(lldb) bt
* thread #16, name = 'AURemoteIO::IOThread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x0000000105479a28 Csound iOS SwiftExamples.debug.dylib`Csound_Render(inRefCon=0x0000000281b48710, ioActionFlags=0x000000016b7ce3dc, inTimeStamp=0x000000016b7ce390, dump=0, inNumberFrames=941, ioData=0x000000010525c520) at CsoundObj.m:369:36
    frame #1: 0x0000000210fc2eac libEmbeddedSystemAUs.dylib`ausdk::AUInputElement::PullInput(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int) + 176
    frame #2: 0x0000000210fa9bec libEmbeddedSystemAUs.dylib`AUInputFormatConverter2::InputProc(OpaqueAudioConverter*, unsigned int*, AudioBufferList*, AudioStreamPacketDescription**, void*) + 160
    frame #3: 0x00000001b621e3e8 AudioToolboxCore`caulk::expected<unsigned int, int> caulk::function_ref<caulk::expected<unsigned int, int> (ACAudioSpan&)>::functor_invoker<acv2::_AudioConverterFillComplexBuffer(OpaqueAudioConverter*, int (*)(OpaqueAudioConverter*, unsigned int*, AudioBufferList*, AudioStreamPacketDescription**, void*), void*, unsigned int*, AudioBufferList*, AudioStreamPacketDescription*, AudioStreamPacketDependencyInfo*)::$_1>(caulk::details::erased_callable<caulk::expected<unsigned int, int> (ACAudioSpan&)> const&, ACAudioSpan&) + 184
    frame #4: 0x00000001b61a26f8 AudioToolboxCore`acv2::AudioConverterChain::ObtainInput(acv2::AudioConverterBase&, unsigned int) + 808
    frame #5: 0x00000001b6314908 AudioToolboxCore`acv2::CBRConverter::ProduceOutput(ACAudioSpan&) + 52
    frame #6: 0x00000001b61a26b8 AudioToolboxCore`acv2::AudioConverterChain::ObtainInput(acv2::AudioConverterBase&, unsigned int) + 744
    frame #7: 0x00000001b62c0a10 AudioToolboxCore`acv2::Resampler2Wrapper::ProduceOutput(ACAudioSpan&) + 228
    frame #8: 0x00000001b61a1dcc AudioToolboxCore`acv2::AudioConverterChain::ProduceOutput(caulk::function_ref<caulk::expected<unsigned int, int> (ACAudioSpan&)>, ACBaseAudioSpan&) + 184
    frame #9: 0x00000001b621df28 AudioToolboxCore`acv2::_AudioConverterFillComplexBuffer(OpaqueAudioConverter*, int (*)(OpaqueAudioConverter*, unsigned int*, AudioBufferList*, AudioStreamPacketDescription**, void*), void*, unsigned int*, AudioBufferList*, AudioStreamPacketDescription*, AudioStreamPacketDependencyInfo*) + 444
    frame #10: 0x0000000210fb62b0 libEmbeddedSystemAUs.dylib`AUConverterBase::RenderBus(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int) + 880
    frame #11: 0x0000000210fafcf0 libEmbeddedSystemAUs.dylib`AURemoteIO::RenderBus(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int) + 196
    frame #12: 0x0000000210f9f0b8 libEmbeddedSystemAUs.dylib`ausdk::AUBase::DoRender(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int, AudioBufferList&) + 1548
    frame #13: 0x0000000210f9febc libEmbeddedSystemAUs.dylib`AURemoteIO::PerformIO(unsigned int, unsigned int, unsigned int, AudioTimeStamp const&, AudioTimeStamp const&, AudioBufferList const*, AudioBufferList*, int&) + 1344
    frame #14: 0x0000000210fa8ea8 libEmbeddedSystemAUs.dylib`_XPerformIO + 340
    frame #15: 0x00000001cabfec20 libAudioToolboxUtility.dylib`mshMIGPerform + 264
    frame #16: 0x00000001cabfe364 libAudioToolboxUtility.dylib`MSHMIGDispatchMessage + 40
    frame #17: 0x0000000211045aa4 libEmbeddedSystemAUs.dylib`void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, AURemoteIO::IOThread::IOThread(AURemoteIO&, caulk::thread::attributes const&, caulk::mach::os_workgroup_managed const&)::'lambda'(), std::__1::tuple<>>>(void*) + 580
    frame #18: 0x00000001f75d66cc libsystem_pthread.dylib`_pthread_start + 148
```

**Comment by Megal** [comment]
Consider following tags (I don't have perms to set them up):
iOS, Csound7, bug

**Comment by vlazzarini** [comment]
Did the examples work in previous commits?

**Comment by vlazzarini** [comment]
I spotted an issue in CsoundObj.m
Fixed in https://github.com/csound/csound/pull/2112

You can try this by replacing the CsoundObj.m in the artefact by this one. Let me know if it works.

**Comment by Megal** [comment]
> I spotted an issue in CsoundObj.m Fixed in [#2112](https://github.com/csound/csound/pull/2112)
> 
> You can try this by replacing the CsoundObj.m in the artefact by this one. Let me know if it works.

I tried to place  CsoundObj.m -> iOS-builds/Csound\ iOS\ Swift\ Examples/Csound\ iOS\ SwiftExamples/csound-iOS/classes/CsoundObj.m

It has 9 compilation errors. 

![Image](https://github.com/user-attachments/assets/4a175862-379b-4d33-a1da-4945a0e3b673)

It might be relevant that change you've mentioned is related to Obj-C Example, but I also have compilation issues with Obj-C Example in this artifact. 
I not sure if swift Example/ObjC Example CsoundObj.m should be the same, but I have 39 diffs between them.

**Comment by vlazzarini** [comment]
Yes, the two files should be the same. I have updated the Swift one now.
The errors you are listing show that you are using Csound 6.x instead of Csound 7.x headers. So you need the correct headers (not sure where these are being picked up from).
I have all objc files compiling correctly here.

Let me see if I can produce an artefact for you to test now.

**Comment by vlazzarini** [comment]
OK, there's a whole lot more wrong. The headers shipped in the artefact are old from 6.x.
I'll fix this before making a new artefact for you.

**Comment by vlazzarini** [comment]
Ok. It was all messed up and needed updating. Old libs mixed with new code etc. causing all sorts of trouble. I think I have everything updated now.  Tested here the ObjC and Swift examples on the emulator.

Here's an artefact for you to try: 
https://github.com/csound/csound/actions/runs/13747332189/artifacts/2717748111
for you to try. This was produced by the updated PR and if it's all working we'll be ready to merge.

EDIT: I tested the builds in this artefact and they are working with Xcode 16.4 and the armv64 simulator using iOS 18.3. I will try on the iphone when I have a cable to connect.

**Comment by Megal** [comment]
@vlazzarini  Thanks for a quick update! I tried example project - it runs on iOS 16 device, and simulators on Apple Silicon, which is great, because csound 6 release haven't had proper Apple Silicon support.

As for example project itself,
I notice an issue for iPhone devices - it is only able to show first test view controller, there is no navigation. 
On iPad there is no such issue, I'm able to run all examples, since there is a master-detail view controller navigation.

**Comment by vlazzarini** [comment]
ok, I'll close this issue and maybe you can open another for the iphone app navigation.
