### ISSUE TITLE
Failure to compile with gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

### ISSUE THREAD

**Issue by gogins** [csound/csound#1609]
In the csound6 branch:
```
mkg@xenakis:~/csound/build$ make
Scanning dependencies of target csound64
[  0%] Building C object CMakeFiles/csound64.dir/OOps/aops.c.o
/home/mkg/csound/OOps/aops.c: In function ‘_isnan’:
/home/mkg/csound/OOps/aops.c:2225:24: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 2225 |    const uint64_t u = *(uint64_t*)&x;
      |                        ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/csound64.dir/build.make:538: CMakeFiles/csound64.dir/OOps/aops.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:494: CMakeFiles/csound64.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
mkg@xenakis:~/csound/build$ 
```
I think that the logic of this test may also be incorrect.

**Comment by jpffitch** [comment]
Looks fine wit PR so closing
