### PR TITLE
Fix building with GMM 5.3

### LINKED ISSUE #920: linear algebra opcode build fails with gmm > 5.1
The build fails with gmm 5.2 (I think it works with gmm 5.1):

```
[ 17%] Building C object Opcodes/hdf5/CMakeFiles/hdf5ops.dir/HDF5IO.c.o
/build/csound/src/csound-6.10.0/Opcodes/linear_algebra.cpp: In member function ‘int la_i_lu_factor_mr_t::init(CSOUND*)’:
/build/csound/src/csound-6.10.0/Opcodes/linear_algebra.cpp:3898:45: error: no matching function for call to ‘lu_factor(gmm::dense_matrix<double>&, std::vector<long unsigned int>&)’
     *isize = gmm::lu_factor(lhs->mr, pivot__);
                                             ^
In file included from /usr/include/gmm/gmm_lapack_interface.h:42:0,
                 from /usr/include/gmm/gmm_kernel.h:52,
                 from /usr/include/gmm/gmm.h:40,
                 from /build/csound/src/csound-6.10.0/Opcodes/linear_algebra.cpp:371:
/usr/include/gmm/gmm_dense_lu.h:129:13: note: candidate: template<class DenseMatrix> gmm::size_type gmm::lu_factor(DenseMatrix&, gmm::lapack_ipvt&)
   size_type lu_factor(DenseMatrix& A, lapack_ipvt& ipvt) {
             ^~~~~~~~~
/usr/include/gmm/gmm_dense_lu.h:129:13: note:   template argument deduction/substitution failed:
/build/csound/src/csound-6.10.0/Opcodes/linear_algebra.cpp:3898:38: note:   cannot convert ‘((la_i_lu_factor_mr_t*)this)->la_i_lu_factor_mr_t::pivot__’ (type ‘std::vector<long unsigned int>’) to type ‘gmm::lapack_ipvt&’
     *isize = gmm::lu_factor(lhs->mr, pivot__);
                                      ^~~~~~~
/build/csound/src/csound-6.10.0/Opcodes/linear_algebra.cpp: In member function ‘int la_k_lu_factor_mr_t::kontrol(CSOUND*)’:
/build/csound/src/csound-6.10.0/Opcodes/linear_algebra.cpp:3930:45: error: no matching function for call to ‘lu_factor(gmm::dense_matrix<double>&, std::vector<long unsigned int>&)’
     *ksize = gmm::lu_factor(lhs->mr, pivot__);
                                             ^
In file included from /usr/include/gmm/gmm_lapack_interface.h:42:0,
                 from /usr/include/gmm/gmm_kernel.h:52,
                 from /usr/include/gmm/gmm.h:40,
                 from /build/csound/src/csound-6.10.0/Opcodes/linear_algebra.cpp:371:
/usr/include/gmm/gmm_dense_lu.h:129:13: note: candidate: template<class DenseMatrix> gmm::size_type gmm::lu_factor(DenseMatrix&, gmm::lapack_ipvt&)
   size_type lu_factor(DenseMatrix& A, lapack_ipvt& ipvt) {
             ^~~~~~~~~
/usr/include/gmm/gmm_dense_lu.h:129:13: note:   template argument deduction/substitution failed:
/build/csound/src/csound-6.10.0/Opcodes/linear_algebra.cpp:3930:38: note:   cannot convert ‘((la_k_lu_factor_mr_t*)this)->la_k_lu_factor_mr_t::pivot__’ (type ‘std::vector<long unsigned int>’) to type ‘gmm::lapack_ipvt&’
     *ksize = gmm::lu_factor(lhs->mr, pivot__);
                                      ^~~~~~~
/build/csound/src/csound-6.10.0/Opcodes/linear_algebra.cpp: In member function ‘int la_i_lu_factor_mc_t::init(CSOUND*)’:
/build/csound/src/csound-6.10.0/Opcodes/linear_algebra.cpp:3958:45: error: no matching function for call to ‘lu_factor(gmm::dense_matrix<std::complex<double> >&, std::vector<long unsigned int>&)’
     *isize = gmm::lu_factor(lhs->mc, pivot__);
                                             ^
In file included from /usr/include/gmm/gmm_lapack_interface.h:42:0,
                 from /usr/include/gmm/gmm_kernel.h:52,
                 from /usr/include/gmm/gmm.h:40,
                 from /build/csound/src/csound-6.10.0/Opcodes/linear_algebra.cpp:371:
/usr/include/gmm/gmm_dense_lu.h:129:13: note: candidate: template<class DenseMatrix> gmm::size_type gmm::lu_factor(DenseMatrix&, gmm::lapack_ipvt&)
   size_type lu_factor(DenseMatrix& A, lapack_ipvt& ipvt) {
             ^~~~~~~~~
/usr/include/gmm/gmm_dense_lu.h:129:13: note:   template argument deduction/substitution failed:
/build/csound/src/csound-6.10.0/Opcodes/linear_algebra.cpp:3958:38: note:   cannot convert ‘((la_i_lu_factor_mc_t*)this)->la_i_lu_factor_mc_t::pivot__’ (type ‘std::vector<long unsigned int>’) to type ‘gmm::lapack_ipvt&’
     *isize = gmm::lu_factor(lhs->mc, pivot__);
                                      ^~~~~~~
/build/csound/src/csound-6.10.0/Opcodes/linear_algebra.cpp: In member function ‘int la_k_lu_factor_mc_t::kontrol(CSOUND*)’:
/build/csound/src/csound-6.10.0/Opcodes/linear_algebra.cpp:3990:45: error: no matching function for call to ‘lu_factor(gmm::dense_matrix<std::complex<double> >&, std::vector<long unsigned int>&)’
     *ksize = gmm::lu_factor(lhs->mc, pivot__);
                                             ^
In file included from /usr/include/gmm/gmm_lapack_interface.h:42:0,
                 from /usr/include/gmm/gmm_kernel.h:52,
                 from /usr/include/gmm/gmm.h:40,
                 from /build/csound/src/csound-6.10.0/Opcodes/linear_algebra.cpp:371:
/usr/include/gmm/gmm_dense_lu.h:129:13: note: candidate: template<class DenseMatrix> gmm::size_type gmm::lu_factor(DenseMatrix&, gmm::lapack_ipvt&)
   size_type lu_factor(DenseMatrix& A, lapack_ipvt& ipvt) {
             ^~~~~~~~~
/usr/include/gmm/gmm_dense_lu.h:129:13: note:   template argument deduction/substitution failed:
/build/csound/src/csound-6.10.0/Opcodes/linear_algebra.cpp:3990:38: note:   cannot convert ‘((la_k_lu_factor_mc_t*)this)->la_k_lu_factor_mc_t::pivot__’ (type ‘std::vector<long unsigned int>’) to type ‘gmm::lapack_ipvt&’
     *ksize = gmm::lu_factor(lhs->mc, pivot__);
                                      ^~~~~~~

```

### PR DESCRIPTION
**Pull request by laserbat**
Since GMM++ doesn't have any reliable way to check version (no GMM_VERSION macro etc) and is not backwards compatible, it would make sense to include a version of it in this repository, so that builds can be consistent and cause less problems.

fixes #920

### CODE REVIEW

**Comment by jpffitch** [comment]
DEoes this compile with earlier GMM?  I see it failed the Travis build

**Comment by laserbat** [comment]
Yeah, I need to do some more tinkering to make it work with older GMM

**Comment by jpffitch** [comment]
Looks like incompatible code
From the Travis log......

home/travis/build/csound/csound/Opcodes/linear_algebra.cpp

/home/travis/build/csound/csound/Opcodes/linear_algebra.cpp: In member function ‘int la_i_lu_factor_mr_t::init(CSOUND*)’:

/home/travis/build/csound/csound/Opcodes/linear_algebra.cpp:3504:39: error: ‘lapack_ipvt’ is not a member of ‘gmm’

     *isize = gmm::lu_factor(lhs->mr, (gmm::lapack_ipvt&) pivot__);

                                       ^

/home/travis/build/csound/csound/Opcodes/linear_algebra.cpp:3504:56: error: expected primary-expression before ‘)’ token

     *isize = gmm::lu_factor(lhs->mr, (gmm::lapack_ipvt&) pivot__);

                                                        ^

**Comment by laserbat** [comment]
I tried to find a decent way to check GMM version, but it doesn't seem possible. I propose including GMM as a third-party library inside csound source tree

**Comment by kunstmusik** [comment]
I think it's not worth managing an independent GMM version when the opcodes that use these will probably be moved out of the core repo (along with HDF5 and a number of others) once package manager is implemented and the installer builds are also moved to a separate repo. (The installer repo can be made to pull in core and other repos, whether compiling source or binary).

**Comment by laserbat** [comment]
I agree that it would be the best to move extra plugins to a separate repo but this seems more like a long-term goal. In the mean time, it wouldn't hurt to have a temporary copy of this library, to ease the transition.

**Comment by gogins** [comment]
This is what I found when I tried to get both versions to compile.

Regards,
Mike

**Comment by vlazzarini** [comment]
@jpffitch  should we merge this and close the issue?

**Comment by vlazzarini** [comment]
Or just close the issue, given @kunstmusik comments?

**Comment by jpffitch** [comment]
Problem is that some repros do not distribute 5.3 or did not when I last looked.  I will check again

⁣Sent from TypeApp ​

**Comment by jpffitch** [comment]
Debian stretch has version 5.2

Not packaged for OpenSuse 15.1 or 15.2

**Comment by vlazzarini** [comment]
In view of this and @kunstmusik, I don't see we can go anywhere with this here. Can I close it?

It looks like the lin algebra opcodes need to have their own third party repo.

**Comment by jpffitch** [comment]
The PR is good for 5.3 but fails on 5.2.  Ideally we should compie one or 
the other via a macro whichis set by a check on the header -- ie which 
compiles.  Could we retain both versions for now and take a cmake option 
as which to compile?

**Comment by vlazzarini** [comment]
I am happy with that solution. Will need some changes after merge.

**Comment by jpffitch** [comment]
#I will have a go.

**Comment by jpffitch** [comment]
1.

**Comment by jpffitch** [comment]
This seems to have been dealt with already

**Comment by jpffitch** [comment]
This is done
