### ISSUE TITLE
Compile of 5.06/7 fails in OOps/remote.c [sf bugs #41]

### ISSUE THREAD

**Issue by kunstmusik** [csound/csound#41]
**Originally reported by Sourceforge User: *anonymous**

Compilation fails on Gentoo Linux (using the ebuild in 5.06) with:

OOps/remote.c: In function 'getIpAddress':
OOps/remote.c:70: error: storage size of 'ifr' isn't known
OOps/remote.c:70: warning: unused variable 'ifr'
OOps/remote.c: In function 'CLopen':
OOps/remote.c:230: warning: implicit declaration of function 'inet_aton'
scons: *** [OOps/remote.o] Error 1

It appears something in the ifreq structure in &lt;linux/if.h&gt; is sufficiently vague that the compiler refuses to give its size. On the other hand, a simple test file containing only the #include &lt;linux/if.h&gt; and struct ifreq ifr; lines compiles fine here...
